services:
  postgres-order-delivery-service:
    image: postgres:16
    container_name: postgres-order-delivery-service
    environment:
      POSTGRES_DB: postgres-orders
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5009:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 30s
      timeout: 30s
      retries: 5
    networks:
      - internal
  
  order-delivery-service-backend:
    image: ghcr.io/annapvasileva/order-delivery-service-backend:main
    container_name: order-delivery-service-backend
    platform: linux/amd64
    networks:
      - internal
    depends_on:
      postgres-order-delivery-service:
        condition: service_healthy
    ports:
      - "5002:5002"
  
  order-delivery-service-frontend:
    image: ghcr.io/annapvasileva/order-delivery-service-frontend:main
    container_name: order-delivery-service-frontend
    platform: linux/amd64
    networks:
      - public
      - internal
    depends_on:
      order-delivery-service-backend:
        condition: service_started
    environment:
      - PORT=3001
    ports:
      - "3001:3001"

  pgadmin:
    container_name: pgadmin-order-delivery
    image: dpage/pgadmin4:latest
    hostname: pgadmin
    restart: unless-stopped
    ports:
      - "5010:80"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=pass
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    networks:
      - internal
      - public

networks:
  public:
    driver: bridge
  internal:
    driver: bridge
    internal: true